<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Version>0.1.0</Version>
    <Authors>桔梗</Authors>
    <Copyright>Copyright (c) 2026 桔梗</Copyright>
    <ModFolderName>Ella.StardewBridge</ModFolderName>
    <EnableModDeploy>false</EnableModDeploy>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
  </ItemGroup>
</Project>
